sonatype-nexus:
  ingress:
    enabled: true
    annotations:
      certmanager.k8s.io/issuer: letsencrypt-issuer
      kubernetes.io/ingress.class: nginx
      kubernetes.io/tls-acme: "true"
  nexusProxy:
    env:
      nexusDockerHost: registry.k8.wildwidewest.xyz
      nexusHttpHost: nexus.k8.wildwidewest.xyz
